using System;
using System.Collections.Generic;
using System.Text;

namespace NerdStore.Vendas.Domain
{
    public class Roteiro
    {
        /* DESENVOLVIMENTO DO DOMINIO DE VENDAS */

        /*PEDIDO - ITEM PEDIDO - VOUCHER */

        /*
          
          UM ITEM DE UM PEDIDO REPRESENTA UM PRODUTO E PODE CONTER MAIS DE UMA UNIDADE INDEPENDENTE DA AÇÃO, UM UTEM PRECISA SER SEMPRE VALIDO:
            POSSUIR: ID E NOME DO PRODUTO, QUANTIDADE ENTRE 1 E 15 UNIDADES, VALOR MAIOR QUE 0

          UM PEDIDO ENQUANTO NÃO INICIADO (PROCESSO DE PAGAMENTO) ESTÁ NO STADO DE RASCUNHO E DEVE PERTENCER A UM CLIENTE.

          1 - ADICIONAR ITEM,
            1.1 - AO ADICIONAR UM ITEM É NECESSARIO CALCULAR O VALOR TOTAL DO PEDIDO
            1.2 - SE UM ITEM JÁ ESTÁ NA LISTA ENTÃO DEVE ACRESCER A QUANTIDADE DO ITEM NO PEDIDO
            1.3 - O ITEM DEVE TER ENTRE 1 E 15 UNIDADES DO PRODUTO

          2 - ATUALIZAÇÃO DO ITEM
            2.1 - O ITEM PRECISA ESTAR NA LISTA PARA SER ATUALIZADO
            2.2 - UM ITEM PODE SER ATUALIZADO CONTENDO MASI OU MENOS UNIDADES DO QUE ANTERIORMENTE
            2.3 - AO ATUALIZAR UM ITEM É NECESSARIO CALCULAR O VALOR TOTAL DO PEDIDO
            2.4 - UM ITEM DEVE PERMANECER ENTRE 1 E 15 UNIDADES DO PRODUTO

          3 - REMOÃO DE ITEM
            3.1 - O ITEM PRECISA ESTAR NA LISTA PARA SER REMOVIDO
            3.2 - AO REMOVER UM ITEM É NECESSARIO CALCULAR O VALOR TOTAL DO PEDIDO

          UM VOUCHER POSSUI UM CÓDIGO ÚNICO E O DESCONTO PODE SER EM PERCENTUAL OU VALOR FIXO
          USAR UMA FLAG INDICANDO QUE UM PEDIDO TEVE UM VOUCHER DE DESCONTO APLICADO E O VALOR DO DESCONTO

          4 - APLICAR VOUCHER DE DESCONTO
            4.1 O VOUCHER SO PODE SER APLICADO SE ESTIVER VÁLIDO, PARA ISTO:
                4.1.1 - DEVE POSSUIR UM CODIGO
                4.1.2 - A DATA DE VALIDADE É SUPERIOR A DATA ATUAL
                4.1.3 - O VOUCHER ESTÁ ATIVO
                4.1.3 - O VOUCHER POSSUI QUANTIDADE DISPONIVEL
            4.2 - CALCULAR O DESONTO CONFORME QUANTIDADE DISPONIVEL
                4.2.1 - VOUCHER COM DESCONTO PERCENTUAL
                4.2.2 - VOUCHER COM DESCONTO EM VALORES (REIAS)
            4.3 - QUANDO O VALOR DOD DESCONTO UKTRAPASSAR O TOTAL DO PEDIDO O PEDIDO RECEBE O VALOR: 0
            4.4 - APÓS A APLICAÇÃO DO VOUCHER O DESCONTO DEVE SER RE-CALCULADO APÓS TODA MODIFICAÃO DA LISTA DE INTES DE PEDIDO
         */

        /* PEDIDO COMMANDS - HANDLER */

        /*
         
            O COMMAND HANDLER DE PEDIDO IRÁ MANIPULAR UM COMMAND PARA CADA INTENÇÃO EM RELAÇÃO AO PEDIDO.
            EM TODOS OS COMANDOS MANIPULADOS DEVEM SER VERIFICADOS:

                SE O COMMAND É VALIDO
                SE O PEDIDO EXISTE
                SE O ITEM DO PEDIDO EXISTE


            NA ALTERAÇÃO DE ESTADO DO PEDIDO:
                
                DEVE SER FEITA VIA REPOSITORIO
                DEVE ENVIAR UM EVENTO

            1 - ADICIONARITEMPEDIDOCOMMAND
                1.1 VERIFICAR SE É UM PEDIDO NOVO OU EM ANDAMENTO
                1.2 VERIFICAR SE O ITEM JÁ FOI ADICIONADO A LISTA




         */
    }
}
